
### GET ALL PRODUCTS 
GET  http://localhost:5000/products


### GET PRODUCT ID WAYS 
GET  http://localhost:5000/products/3



###CREATE PRODUCT
POST  http://localhost:5000/products
Content-Type: application/json

{
    "title": "Product 34",
    "price": 345
}


### UPDATE PRODUCT
PATCH   http://localhost:5000/products/1
Content-Type: application/json

{
    "title": "Product UPDATE",
    "price": 123
}



### DELETE PRODUCT 
DELETE   http://localhost:5000/products/1